# Local development overrides
replicaCount: 1

image:
  registry: localhost:5000
  repository: eva
  tag: local
  pullPolicy: Always

resources:
  limits:
    cpu: 256m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5

env:
  - name: NODE_ENV
    value: "development"
  - name: VITE_BACKEND_URL
    value: "http://pandora-pandora:8080"
