extend type Query {
    getVenue(id: Int!): VenueView!
    searchVenues(count:Int!, offset:Int!, filter: VenueFilter!, sort: String!): VenuePage!
}

type VenuePage {
    content: [VenueView!]!
    pageable: Pageable!
    total: Int!
}

input VenueFilter {
    searchTerm: String!,
    properties: [String!]!,
    locationAmenities: [String!]!,
    cities: [String!]!,
    surfaceTypes: [String!]!,
    venueTypes: [String!]!
}

type LazyLocationView {
    id : ID!
    name: String!
    description: String!
    website: String!
    geom: PointView!
    address: Address!
    contact: Contact!
    amenities: [String!]!
}

type VenueView {
    id: ID!
    name: String!
    description: String!
    venueType: String!
    surfaceType: String!
    properties: [String!]!
    location: LazyLocationView!
}