spring:
  thymeleaf:
    enabled: false
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      locations: classpath*:graphql/**/
    cors:
      allowed-origins: "*"
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/avatar
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    web: debug
    graphql: debug

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000